# permissions for end users to edit dnsmasqdhcphostsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnsmasqdhcphostset-editor-role
rules:
- apiGroups:
  - dnsmasq.kvaps.cf
  resources:
  - dnsmasqdhcphostsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dnsmasq.kvaps.cf
  resources:
  - dnsmasqdhcphostsets/status
  verbs:
  - get
