# permissions for end users to edit dnsmasqdhcpoptionsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnsmasqdhcpoptionset-editor-role
rules:
- apiGroups:
  - dnsmasq.kvaps.cf
  resources:
  - dnsmasqdhcpoptionsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dnsmasq.kvaps.cf
  resources:
  - dnsmasqdhcpoptionsets/status
  verbs:
  - get
