# permissions for end users to view dnsmasqhostsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnsmasqhostset-viewer-role
rules:
- apiGroups:
  - dnsmasq.kvaps.cf
  resources:
  - dnsmasqhostsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dnsmasq.kvaps.cf
  resources:
  - dnsmasqhostsets/status
  verbs:
  - get
